// Generated by scripts/sync-collection.mjs from verified avatar metadata.
export const GENERATED_CAST = [
  {
    "name": "animal-bear",
    "category": "animal",
    "en": "bear",
    "th": "หมี"
  },
  {
    "name": "animal-cat",
    "category": "animal",
    "en": "cat",
    "th": "แมว"
  },
  {
    "name": "animal-chick",
    "category": "animal",
    "en": "chick",
    "th": "ลูกเจี๊ยบ"
  },
  {
    "name": "animal-cow",
    "category": "animal",
    "en": "cow",
    "th": "วัว"
  },
  {
    "name": "animal-deer",
    "category": "animal",
    "en": "deer",
    "th": "กวาง"
  },
  {
    "name": "animal-dog",
    "category": "animal",
    "en": "dog",
    "th": "สุนัข"
  },
  {
    "name": "animal-duck",
    "category": "animal",
    "en": "duck",
    "th": "เป็ด"
  },
  {
    "name": "animal-elephant",
    "category": "animal",
    "en": "elephant",
    "th": "ช้าง"
  },
  {
    "name": "animal-fox",
    "category": "animal",
    "en": "fox",
    "th": "จิ้งจอก"
  },
  {
    "name": "animal-frog",
    "category": "animal",
    "en": "frog",
    "th": "กบ"
  },
  {
    "name": "animal-giraffe",
    "category": "animal",
    "en": "giraffe",
    "th": "ยีราฟ"
  },
  {
    "name": "animal-hamster",
    "category": "animal",
    "en": "hamster",
    "th": "แฮมสเตอร์"
  },
  {
    "name": "animal-hedgehog",
    "category": "animal",
    "en": "hedgehog",
    "th": "เม่น"
  },
  {
    "name": "animal-hippo",
    "category": "animal",
    "en": "hippo",
    "th": "ฮิปโป"
  },
  {
    "name": "animal-koala",
    "category": "animal",
    "en": "koala",
    "th": "โคอาลา"
  },
  {
    "name": "animal-lion",
    "category": "animal",
    "en": "lion",
    "th": "สิงโต"
  },
  {
    "name": "animal-mouse",
    "category": "animal",
    "en": "mouse",
    "th": "หนู"
  },
  {
    "name": "animal-otter",
    "category": "animal",
    "en": "otter",
    "th": "นาก"
  },
  {
    "name": "animal-owl",
    "category": "animal",
    "en": "owl",
    "th": "นกฮูก"
  },
  {
    "name": "animal-panda",
    "category": "animal",
    "en": "panda",
    "th": "แพนด้า"
  },
  {
    "name": "animal-penguin",
    "category": "animal",
    "en": "penguin",
    "th": "เพนกวิน"
  },
  {
    "name": "animal-pug",
    "category": "animal",
    "en": "pug",
    "th": "ปั๊ก"
  },
  {
    "name": "animal-rabbit",
    "category": "animal",
    "en": "rabbit",
    "th": "กระต่าย"
  },
  {
    "name": "animal-raccoon",
    "category": "animal",
    "en": "raccoon",
    "th": "แรคคูน"
  },
  {
    "name": "animal-red-panda",
    "category": "animal",
    "en": "red panda",
    "th": "แพนด้าแดง"
  },
  {
    "name": "animal-seal",
    "category": "animal",
    "en": "seal",
    "th": "แมวน้ำ"
  },
  {
    "name": "animal-sheep",
    "category": "animal",
    "en": "sheep",
    "th": "แกะ"
  },
  {
    "name": "animal-sloth",
    "category": "animal",
    "en": "sloth",
    "th": "สลอธ"
  },
  {
    "name": "animal-squirrel",
    "category": "animal",
    "en": "squirrel",
    "th": "กระรอก"
  },
  {
    "name": "animal-tiger",
    "category": "animal",
    "en": "tiger",
    "th": "เสือ"
  },
  {
    "name": "human-afro",
    "category": "human",
    "en": "afro",
    "th": "ผมแอฟโฟร"
  },
  {
    "name": "human-artist",
    "category": "human",
    "en": "artist",
    "th": "ศิลปิน"
  },
  {
    "name": "human-astronaut",
    "category": "human",
    "en": "astronaut",
    "th": "นักบินอวกาศ"
  },
  {
    "name": "human-bald",
    "category": "human",
    "en": "bald",
    "th": "ศีรษะล้าน"
  },
  {
    "name": "human-beanie",
    "category": "human",
    "en": "beanie",
    "th": "หมวกไหมพรม"
  },
  {
    "name": "human-bearded",
    "category": "human",
    "en": "bearded",
    "th": "หนวดเครา"
  },
  {
    "name": "human-black-glasses",
    "category": "human",
    "en": "black glasses",
    "th": "แว่นดำ"
  },
  {
    "name": "human-blond",
    "category": "human",
    "en": "blond",
    "th": "ผมบลอนด์"
  },
  {
    "name": "human-bob",
    "category": "human",
    "en": "bob",
    "th": "ผมบ๊อบ"
  },
  {
    "name": "human-builder",
    "category": "human",
    "en": "builder",
    "th": "ช่างก่อสร้าง"
  },
  {
    "name": "human-bun",
    "category": "human",
    "en": "bun",
    "th": "ผมมวย"
  },
  {
    "name": "human-cap",
    "category": "human",
    "en": "cap",
    "th": "หมวกแก๊ป"
  },
  {
    "name": "human-chef",
    "category": "human",
    "en": "chef",
    "th": "เชฟ"
  },
  {
    "name": "human-curly-glasses",
    "category": "human",
    "en": "curly glasses",
    "th": "ผมหยิกและแว่น"
  },
  {
    "name": "human-doctor",
    "category": "human",
    "en": "doctor",
    "th": "แพทย์"
  },
  {
    "name": "human-freckles",
    "category": "human",
    "en": "freckles",
    "th": "กระ"
  },
  {
    "name": "human-grandfather",
    "category": "human",
    "en": "grandfather",
    "th": "คุณปู่"
  },
  {
    "name": "human-grandmother",
    "category": "human",
    "en": "grandmother",
    "th": "คุณย่า"
  },
  {
    "name": "human-headscarf",
    "category": "human",
    "en": "headscarf",
    "th": "ผ้าโพกศีรษะ"
  },
  {
    "name": "human-hijab",
    "category": "human",
    "en": "hijab",
    "th": "ฮิญาบ"
  },
  {
    "name": "human-hoodie",
    "category": "human",
    "en": "hoodie",
    "th": "เสื้อฮู้ด"
  },
  {
    "name": "human-locs",
    "category": "human",
    "en": "locs",
    "th": "ผมล็อกมัดขึ้น"
  },
  {
    "name": "human-nurse",
    "category": "human",
    "en": "nurse",
    "th": "พยาบาล"
  },
  {
    "name": "human-pilot",
    "category": "human",
    "en": "pilot",
    "th": "นักบิน"
  },
  {
    "name": "human-pixie",
    "category": "human",
    "en": "pixie",
    "th": "ผมพิกซี"
  },
  {
    "name": "human-ponytail",
    "category": "human",
    "en": "ponytail",
    "th": "ผมหางม้า"
  },
  {
    "name": "human-silver-bob",
    "category": "human",
    "en": "silver bob",
    "th": "ผมบ๊อบสีเงิน"
  },
  {
    "name": "human-student",
    "category": "human",
    "en": "student",
    "th": "นักเรียน"
  },
  {
    "name": "human-turban",
    "category": "human",
    "en": "turban",
    "th": "ผ้าโพกแบบเทอร์บัน"
  },
  {
    "name": "human-wizard",
    "category": "human",
    "en": "wizard",
    "th": "พ่อมด"
  }
] as const
